// Generated by CoffeeScript 1.8.0
(function() {
  var Server, bodyParser, express;

  express = require('express');

  bodyParser = require('body-parser');

  Server = (function() {
    function Server() {
      this._resources = [];
      this._server = express();
      this._server.use(bodyParser());
      this._server.on("error", function(err) {
        return console.error(err);
      });
      this._server.get("/api", (function(_this) {
        return function(req, res) {
          return res.send(_this._resources.map(function(resource) {
            return {
              name: resource.name(),
              url: "/api/" + (resource.pluralName())
            };
          }));
        };
      })(this));
      this._server.get("/api/:resource", (function(_this) {
        return function(req, res) {
          return _this.find(req.params.resource, function(resource) {
            if (!resource) {
              return res.send(404);
            }
            return res.send(resource.all());
          });
        };
      })(this));
      this._server.get("/api/:resource/:id", (function(_this) {
        return function(req, res) {
          return _this.find(req.params.resource, function(resource) {
            var data;
            if (!resource) {
              return res.send(404);
            }
            if (!(data = resource.find(req.params.id))) {
              res.statusCode = 404;
              return res.send("No " + (resource.name()) + " with id " + req.params.id);
            }
            return res.send(data);
          });
        };
      })(this));
      this._server.post("/api/:resource", (function(_this) {
        return function(req, res) {
          return _this.find(req.params.resource, function(resource) {
            var data;
            if (!resource) {
              return res.send(404);
            }
            data = req.body;
            resource.add(data);
            return res.send(200);
          });
        };
      })(this));
      this._server.put("/api/:resource/:id", (function(_this) {
        return function(req, res) {
          return _this.find(req.params.resource, function(resource) {
            if (!resource) {
              return res.send(404);
            }
            if (resource.update(req.params.id, req.body)) {
              return res.send(200);
            } else {
              res.statusCode = 404;
              return res.send("No " + (resource.name()) + " with id " + req.params.id);
            }
          });
        };
      })(this));
      this._server["delete"]("/api/:resource/:id", (function(_this) {
        return function(req, res) {
          return _this.find(req.params.resource, function(resource) {
            if (!resource) {
              return res.send(404);
            }
            if (resource.remove(req.params.id)) {
              return res.send(200);
            } else {
              res.statusCode = 404;
              return res.send("No " + (resource.name()) + " with id " + req.params.id);
            }
          });
        };
      })(this));
    }

    Server.prototype.find = function(path, cb) {
      var resource, _i, _len, _ref;
      _ref = this._resources;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        resource = _ref[_i];
        if (resource.pluralName() === path) {
          return cb(resource);
        }
      }
      return cb(null);
    };

    Server.prototype.listen = function(port) {
      if (port == null) {
        port = 3000;
      }
      this._server.listen(port);
      return this;
    };

    Server.prototype.register = function(resource) {
      this._resources = this._resources.concat([resource]);
      return this;
    };

    return Server;

  })();

  module.exports = Server;

}).call(this);
